# The default directories
directories = [
  "conf", 
  "models", 
  "modules/middleware", 
  "modules/base",
  "modules/settings", 
  "templates", 
  "public/js", 
  "public/css", 
  "public/imgs", 
  "routers"
]

# Option to include a readme file on project init
[readme]
enabled = true
format = "md"

# This will git init the project on create
[git]
enabled = true
